version: '3.8'

services:
  # Base de datos MySQL (MASTER)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-master.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql-master-init.sql:/docker-entrypoint-initdb.d/01-master-init.sql
    restart: always

  # Base de datos MySQL (SLAVE/REPLICA)
  db-slave:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
    ports:
      - "3307:3306"
    volumes:
      - db_slave_data:/var/lib/mysql
      - ./mysql-slave.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql-slave-init.sql:/docker-entrypoint-initdb.d/01-slave-init.sql
    restart: always
    depends_on:
      - db

  # Primera instancia de la aplicación web (peso 3 - 50% del tráfico)
  web1:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/inventario
    depends_on:
      - db
    restart: always

  # Segunda instancia de la aplicación web (peso 2 - 33% del tráfico)
  web2:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/inventario
    depends_on:
      - db
    restart: always

  # Tercera instancia de la aplicación web (peso 1 - 17% del tráfico)
  web3:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/inventario
    depends_on:
      - db
    restart: always

  # Balanceador de carga NGINX
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
      - web3
    restart: always

  # Servicio para configurar automáticamente la replicación
  replication-setup:
    image: mysql:8.0
    command: >
      sh -c "
        apk add --no-cache bash &&
        chmod +x /setup-replication.sh &&
        /setup-replication.sh
      "
    volumes:
      - ./setup-replication.sh:/setup-replication.sh
    depends_on:
      - db
      - db-slave
    restart: "no"

  # phpMyAdmin para gestión de la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db,db-slave
      PMA_VERBOSE_1: Master
      PMA_VERBOSE_2: Slave
      PMA_USER: root
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
      - db-slave
    restart: always

volumes:
  db_data:
  db_slave_data: 